#!/bin/sh
peer=$(pwd)
libs=
plx=$peer/../../Plexus
sauer=$peer/../SauerbratenRemote
build=/tmp/plexus-build
version=dist/version

if [ "$1" = -clean ] ; then
	rm -rf $build
fi

rm -f /tmp/plexus.jar
mkdir -p $build/dist
cd $build

for i in $peer/lib/*.jar ; do
	if [ ! $version -nt $i ] ; then
		echo extracting $i
		unzip -o $i
		if [ -d META-INF ] ; then
			mv META-INF META-INF-$(basename $i .jar)
		fi
	else
		echo not extracting $i because it is already there
	fi
done
cp -r $peer/bin/* .
cp -r $plx/bin/* .
cp $sauer/src/sauer_client dist/sauerbraten_plexus_linux

echo "PLEXUS BUILD $(date)" > $version

rm -f $build/dist/manifest
cd $build
find dist -type f >> dist/manifest
cd $build
zip -9rDXq /tmp/plexus.jar *
