#!/bin/sh
if [ $# != 1 ] ; then
	echo usage: $(basename $0) sauerConfig
	exit 1
fi
cfg="$1"
if ! expr "$cfg" : "/.*" > /dev/null 2>&1 ; then
	cfg="$(pwd)/$cfg"
fi
dirbase=/tmp/sauer.tmp
dir=$dirbase
count=0
while [ -e "$dir" ] ; do
	count=$(expr $count + 1)
	dir="$dirbase-$count"
done
mkdir "$dir"
cd "$dir"
ln -s /media/sda5/Download/3D/sauerbraten/sauerbraten_2007_12_24/sauerbraten/* .
rm -f autoexec.cfg
ln -s "$cfg" autoexec.cfg
./sauer_client -t
rm -rf "$dir"
